name: Update Release Info

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-release-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release info
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const latest = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const asset = latest.data.assets[0];
            return {
              tag: latest.data.tag_name,
              name: latest.data.name,
              asset_url: asset.browser_download_url,
              asset_name: asset.name
            };

      - name: Download asset
        run: |
          curl -L "${{ steps.release.outputs.asset_url }}" -o release_asset

      - name: Compute SHA256 hash
        id: hash
        run: |
          HASH=$(sha256sum release_asset | awk '{ print $1 }')
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"

      - name: Write release info to file
        run: |
          echo "Repository: ${{ github.repository }}" > release_info.txt
          echo "Tag: ${{ steps.release.outputs.tag }}" >> release_info.txt
          echo "Asset: ${{ steps.release.outputs.asset_name }}" >> release_info.txt
          echo "SHA256: ${{ steps.hash.outputs.hash }}" >> release_info.txt

      - name: Commit and push release_info.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add release_info.txt
          git commit -m "Update release_info.txt for ${{ steps.release.outputs.tag }}" || echo "No changes to commit"
          git push
